import { StoreProvider } from "@/providers/StoreProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  chatHistory,
}: Readonly<{
  children: React.ReactNode;
  chatHistory: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider 
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
            <StoreProvider>
          <main className="w-[350px] md:w-[765px] lg:w-screen h-screen flex  justify-center
          overflow-hidden
          mx-auto">
              {chatHistory}
              {children}
          </main>
            </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
